@Library('jenkins-ci-automation@staging') _
BlibliPipeline {
  type = "java11"
  sonar.serverId="sonar9-gcp"
  deploy_branch_regex = "(master|release/.+)"
  application.tribe = "tribe name" //Replace tribe name character with respective application tribe name
  application.squad = "squad name" //Replace squad name character with respective application squad name
  application.service_name = "{artifactId}"
  application.dev_repo = "https://bitbucket.org/sample.git"
  application.deployment_repo.nonprod = "non prod deployment_repo url"
  application.deployment_repo.prod = "prod deployment_repo url"
}